### ISSUE TITLE
Cannot open the application without root permission (sudo)

### ISSUE THREAD

**Issue by chmnchiang** [Yubico/yubioath-flutter#1141]
## Description

When running the application with `authenticator --log-level DEBUG`, the main screen never appears. When running with `sudo authenticator --log-level DEBUG` the application correctly starts and the main UI is their.

## Steps to reproduce

My linux:

```shell
$ uname -a
Linux <hostname> 6.4.3-arch1-2 #1 SMP PREEMPT_DYNAMIC Sat, 15 Jul 2023 19:25:49 +0000 x86_64 GNU/Linux

$ sudo udevadm --version
253

$ systemctl status pcscd
● pcscd.service - PC/SC Smart Card Daemon
     Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; preset: disabled)
     Active: active (running) since Tue 2023-08-01 23:28:28 PDT; 6min ago
TriggeredBy: ● pcscd.socket
       Docs: man:pcscd(8)
   Main PID: 7833 (pcscd)
      Tasks: 12 (limit: 38319)
     Memory: 7.1M
        CPU: 546ms
     CGroup: /system.slice/pcscd.service
             └─7833 /usr/bin/pcscd --foreground --auto-exit

Aug 01 23:28:28 <hostname> systemd[1]: Started PC/SC Smart Card Daemon.
Aug 01 23:28:30 <hostname> pcscd[7833]: 00000000 winscard.c:281:SCardConnect() Error Reader Exclusive
Aug 01 23:28:30 <hostname> pcscd[7833]: 00003691 winscard.c:281:SCardConnect() Error Reader Exclusive

```

As you can see, `pcscd` is started (though there are some errors. Not sure if that is related.)

Running with user permission:

```
$ authenticator --log-level DEBUG

<... logs omitted ...>

23:36:39.555 [helper.ykman.logging] INFO: Logging at level: DEBUG
23:36:39.555 [helper.ykman.logging] WARNING: 
#############################################################################
#                                                                           #
# WARNING: Sensitive data may be logged!                                    #
# Some personally identifying information may be logged, such as usernames! #
#                                                                           #
#############################################################################
23:36:39.555 [helper.helper.device] INFO: Log level set to: DEBUG
23:36:39.555 [desktop.init] INFO: Helper log level set
23:36:39.633 [helper.ykman.hid.linux] CONFIG: Couldn't read HID descriptor for /dev/hidraw11
Traceback (most recent call last):
  File "ykman/hid/linux.py", line 117, in list_devices
PermissionError: [Errno 13] Permission denied: '/dev/hidraw11'
23:36:39.633 [helper.ykman.hid.linux] CONFIG: Couldn't read HID descriptor for /dev/hidraw10
Traceback (most recent call last):
  File "ykman/hid/linux.py", line 117, in list_devices
... <lines omitted> ...
Traceback (most recent call last):
  File "fido2/hid/linux.py", line 98, in list_descriptors
  File "fido2/hid/linux.py", line 55, in get_descriptor
PermissionError: [Errno 13] Permission denied: '/dev/hidraw5'
23:36:39.700 [helper.fido2.hid.linux] CONFIG: Failed opening device /dev/hidraw4
Traceback (most recent call last):
  File "fido2/hid/linux.py", line 98, in list_descriptors
  File "fido2/hid/linux.py", line 55, in get_descriptor
PermissionError: [Errno 13] Permission denied: '/dev/hidraw4'
23:36:39.700 [helper.fido2.hid.linux] CONFIG: Failed opening device /dev/hidraw3
Traceback (most recent call last):
  File "fido2/hid/linux.py", line 98, in list_descriptors
  File "fido2/hid/linux.py", line 55, in get_descriptor
PermissionError: [Errno 13] Permission denied: '/dev/hidraw3'
23:36:39.700 [helper.fido2.hid.linux] CONFIG: Failed opening device /dev/hidraw0
Traceback (most recent call last):
  File "fido2/hid/linux.py", line 98, in list_descriptors
  File "fido2/hid/linux.py", line 55, in get_descriptor
PermissionError: [Errno 13] Permission denied: '/dev/hidraw0'
23:36:39.819 [helper.helper.device] CONFIG: State changed (was=0, now=-5725989826399839559)
23:36:39.820 [helper.ykman.device] CONFIG: Add device for <class 'yubikit.core.smartcard.SmartCardConnection'>: ScardYubiKeyDevice(pid=0407, fingerprint='Yubico YubiKey OTP+FIDO+CCID 00 00')
23:36:39.849 [helper.yubikit.support] CONFIG: Attempting to read device info, using ScardSmartCardConnection
23:36:39.850 [helper.yubikit.management] CONFIG: Management session initialized for connection=ScardSmartCardConnection, version=5.4.3
23:36:39.852 [helper.yubikit.support] CONFIG: Read info: DeviceInfo(...)
23:36:39.852 [helper.yubikit.support] CONFIG: Device info, after tweaks: DeviceInfo(...)
23:36:39.855 [helper.ykman.device] CONFIG: Resolved device 22678183
23:36:39.916 [helper.ykman.device] CONFIG: Add device for <class 'yubikit.core.otp.OtpConnection'>: OtpYubiKeyDevice(pid=0407, fingerprint='/dev/hidraw1')
23:36:39.973 [helper.ykman.device] CONFIG: Add device for <class 'fido2.ctap.CtapDevice'>: CtapYubiKeyDevice(pid=0407, fingerprint='/dev/hidraw2')
23:36:39.973 [helper.helper.device] CONFIG: State updated: {state[1]}
23:36:39.973 [desktop.devices] INFO: USB state change
{"data": ...}
23:36:39.974 [helper.helper.base] CONFIG: created child: 22678183
23:36:40.001 [helper.yubikit.support] CONFIG: Attempting to read device info, using ScardSmartCardConnection
23:36:40.002 [helper.yubikit.management] CONFIG: Management session initialized for connection=ScardSmartCardConnection, version=5.4.3
23:36:40.004 [helper.yubikit.support] CONFIG: Read info: DeviceInfo(...)
23:36:40.004 [helper.yubikit.support] CONFIG: Device info, after tweaks: DeviceInfo(...)
23:36:40.008 [desktop.devices] INFO: USB state updated, unaccounted for: {}
23:36:40.024 [helper.helper.base] CONFIG: created child: ccid
23:36:40.025 [helper.yubikit.core.smartcard] CONFIG: Touch workaround enabled=False
23:36:40.025 [helper.yubikit.oath] CONFIG: OATH session initialized (version=5.4.3, has_key=False)
23:36:40.025 [helper.helper.base] CONFIG: created child: oath
23:36:40.025 [desktop.oath.state] DEBUG: application status
{"data": ...}
23:36:40.025 [desktop.oath.state] DEBUG: OATH notifier discarded
23:36:40.026 [desktop.oath.state] DEBUG: No OATH state, refresh immediately
23:36:40.026 [desktop.oath.state] DEBUG: refreshing credentials...
23:36:40.026 [desktop.oath.state] DEBUG: No OATH state, refresh immediately
23:36:40.026 [desktop.oath.state] DEBUG: refreshing credentials...
23:36:40.036 [helper.yubikit.oath] CONFIG: Calculating all codes for time=1690958200
23:36:40.051 [helper.helper.base] CONFIG: created child: accounts
23:36:40.051 [helper.yubikit.oath] CONFIG: Calculating all codes for time=1690958200
23:36:40.067 [desktop.oath.state] DEBUG: Entries
{"entries":[{"credential":{...},"code":{...}}, ...]}
23:36:40.067 [desktop.oath.state] DEBUG: Schedule refresh in 19933ms
23:36:40.067 [helper.yubikit.oath] CONFIG: Calculating all codes for time=1690958200
23:36:40.083 [desktop.oath.state] DEBUG: Entries
{"entries":[{"credential":{...},"code":{...}}, ...]}
```

The strange things is that I could see the credential being logged. Just that the main UI never appeared.

When running with sudo, the logs is basically the same except that there are no `PermissionError` when reading `/dev/hidrawX` in the beginning.

I also find out that when `pcscd` is enabled, gpg stops working

```
$ gpg --card-status      
gpg: selecting card failed: No such device
gpg: OpenPGP card not available: No such device
```

I guess they are mutually exclusive?

**Comment by AdamVe** [comment]
Thank you for the detailed report. Please try the following steps to fix the issue and let me know if that helped
1. quit the app started as root, if it is running
2. delete following file `~/.local/share/authenticator/shared_preferences.json`
3. run the app as without the root permissions

**Comment by chmnchiang** [comment]
Can confirm that the app opened normally after removing `~/.local/share/authenticator/shared_preferences.json`. I guess it is because I opened the app with sudo before, which tainted the setting file? Thank you.

**Comment by AdamVe** [comment]
Thank you for confirming! We suspect that your particular issue was caused by “hiding” the app. On Linux you can do it with the `Ctrl`+`W` keyboard shortcut. The app hides into the desktop environment's systray, where you can use a context menu to access your pinned accounts or show the app window again. The state is saved into app preferences, so next time you start the app it will start hidden. Some Linux distributions don’t come with systray support by default and hiding the app will make the app window not appear, similar to what you described. We are working on an improvement for this for the next release. If you again cannot start the app, please remove the preferences.
