### ISSUE TITLE
Cannot open application

### ISSUE THREAD

**Issue by ankarhem** [Yubico/yubioath-flutter#1247]
Cannot open yubico authenticator, the process will continue to be alive but unable to open. Tried reinstalling, rebooting etc.

OS: MacOS Sonoma 14.1

```
2023-11-02 16:08:48.950 Yubico Authenticator[52994:247465] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
16:08:48.978 [desktop.init] INFO: Logging initialized, outputting to stderr
16:08:48.982 [desktop.init] INFO: Starting Helper subprocess: /Applications/Yubico Authenticator.app/Contents/Resources/helper-arm64/authenticator-helper
16:08:48.986 [desktop.init] INFO: Helper process started
16:08:49.348 [helper.ykman.logging] INFO: Logging at level: INFO
16:08:49.349 [helper.helper.device] INFO: Log level set to: INFO
16:08:49.349 [desktop.init] INFO: Helper log level set
16:08:49.410 [helper] ERROR: sysmon request failed with error: sysmond service not found
16:08:49.410 [helper] ERROR: pkill: Cannot get process list
16:08:49.411 [helper.ykman.device] WARNING: Failed opening device
Traceback (most recent call last):
  File "ykman/device.py", line 171, in add
  File "ykman/pcsc/__init__.py", line 88, in open_connection
  File "ykman/pcsc/__init__.py", line 100, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 106, in __init__
  File "smartcard/CardConnectionDecorator.py", line 54, in connect
  File "smartcard/pcsc/PCSCCardConnection.py", line 122, in connect
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation.
16:08:49.466 [desktop.devices] INFO: USB state change
{"data":{"state":3978655847354049853,"pids":{"1031":1}},"actions":["get","scan"],"children":{"REDACTED":{"pid":1031,"name":"YubiKey 5C NFC","serial":REDACTED}}}
16:08:49.472 [helper] ERROR: sysmon request failed with error: sysmond service not found
16:08:49.472 [helper] ERROR: pkill: Cannot get process list
16:08:49.473 [helper.ykman.device] WARNING: Failed opening device
Traceback (most recent call last):
  File "ykman/device.py", line 198, in connect
  File "ykman/pcsc/__init__.py", line 88, in open_connection
  File "ykman/pcsc/__init__.py", line 100, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 106, in __init__
  File "smartcard/CardConnectionDecorator.py", line 54, in connect
  File "smartcard/pcsc/PCSCCardConnection.py", line 122, in connect
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation.
16:08:50.485 [helper] ERROR: sysmon request failed with error: sysmond service not found
16:08:50.485 [helper] ERROR: pkill: Cannot get process list
16:08:50.486 [helper.ykman.device] WARNING: Failed opening device
Traceback (most recent call last):
  File "ykman/device.py", line 198, in connect
  File "ykman/pcsc/__init__.py", line 88, in open_connection
  File "ykman/pcsc/__init__.py", line 100, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 106, in __init__
  File "smartcard/CardConnectionDecorator.py", line 54, in connect
  File "smartcard/pcsc/PCSCCardConnection.py", line 122, in connect
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation.
16:08:51.503 [helper] ERROR: sysmon request failed with error: sysmond service not found
16:08:51.503 [helper] ERROR: pkill: Cannot get process list
16:08:51.504 [helper.ykman.device] WARNING: Failed opening device
Traceback (most recent call last):
  File "ykman/device.py", line 198, in connect
  File "ykman/pcsc/__init__.py", line 88, in open_connection
  File "ykman/pcsc/__init__.py", line 100, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 106, in __init__
  File "smartcard/CardConnectionDecorator.py", line 54, in connect
  File "smartcard/pcsc/PCSCCardConnection.py", line 122, in connect
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation.
16:08:52.530 [helper] ERROR: sysmon request failed with error: sysmond service not found
16:08:52.530 [helper] ERROR: pkill: Cannot get process list
16:08:52.532 [helper.ykman.device] WARNING: Failed opening device
Traceback (most recent call last):
  File "ykman/device.py", line 198, in connect
  File "ykman/pcsc/__init__.py", line 88, in open_connection
  File "ykman/pcsc/__init__.py", line 100, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 106, in __init__
  File "smartcard/CardConnectionDecorator.py", line 54, in connect
  File "smartcard/pcsc/PCSCCardConnection.py", line 122, in connect
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation.
16:08:53.556 [helper] ERROR: sysmon request failed with error: sysmond service not found
16:08:53.556 [helper] ERROR: pkill: Cannot get process list
16:08:53.558 [helper.ykman.device] WARNING: Failed opening device
Traceback (most recent call last):
  File "ykman/device.py", line 198, in connect
  File "ykman/pcsc/__init__.py", line 88, in open_connection
  File "ykman/pcsc/__init__.py", line 100, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 106, in __init__
  File "smartcard/CardConnectionDecorator.py", line 54, in connect
  File "smartcard/pcsc/PCSCCardConnection.py", line 122, in connect
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation.
16:08:54.580 [helper] ERROR: sysmon request failed with error: sysmond service not found
16:08:54.580 [helper] ERROR: pkill: Cannot get process list
16:08:54.581 [helper.ykman.device] WARNING: Failed opening device
Traceback (most recent call last):
  File "ykman/device.py", line 198, in connect
  File "ykman/pcsc/__init__.py", line 88, in open_connection
  File "ykman/pcsc/__init__.py", line 100, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 106, in __init__
  File "smartcard/CardConnectionDecorator.py", line 54, in connect
  File "smartcard/pcsc/PCSCCardConnection.py", line 122, in connect
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation.
16:08:54.582 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.smartcard.SmartCardConnection'>
Traceback (most recent call last):
  File "helper/device.py", line 280, in get_data
  File "ykman/device.py", line 270, in open_connection
  File "ykman/device.py", line 232, in connect
  File "ykman/device.py", line 232, in connect
  File "ykman/device.py", line 232, in connect
  [Previous line repeated 2 more times]
  File "ykman/device.py", line 234, in connect
ValueError: Failed to connect to the device
16:08:54.637 [desktop.devices] INFO: USB state updated, unaccounted for: {}
16:08:54.665 [helper] ERROR: sysmon request failed with error: sysmond service not found
16:08:54.665 [helper] ERROR: pkill: Cannot get process list
16:08:54.665 [helper.ykman.device] WARNING: Failed opening device
Traceback (most recent call last):
  File "ykman/device.py", line 198, in connect
  File "ykman/pcsc/__init__.py", line 88, in open_connection
  File "ykman/pcsc/__init__.py", line 100, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 96, in _open_smartcard_connection
  File "ykman/pcsc/__init__.py", line 106, in __init__
  File "smartcard/CardConnectionDecorator.py", line 54, in connect
  File "smartcard/pcsc/PCSCCardConnection.py", line 122, in connect
smartcard.Exceptions.CardConnectionException: Unable to connect with protocol: T0 or T1. Sharing violation.
16:08:54.666 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 289, in ccid
  File "helper/device.py", line 273, in _create_connection
  File "ykman/device.py", line 270, in open_connection
  File "ykman/device.py", line 234, in connect
ValueError: Failed to connect to the device
```

**Comment by adam-hurwitz** [comment]
Thank you for creating this issue @ankarhem!

[Someone's solution in r/yubikey](https://www.reddit.com/r/yubikey/comments/17on87o/comment/k83ybyt/?utm_source=share&utm_medium=web2x&context=3) has solved this issue for me so far. 

The app window was being hidden and I needed to select the Yubico app from the menu icon at the top of the screen. Now when I launch the Yubico Authenticator app from Spotlight Search for example the app opens successfully.
