### ISSUE TITLE
ERROR com.yubico.authenticator.Log -  Failed to add account

### ISSUE THREAD

**Issue by mathieu-pillar** [Yubico/yubioath-flutter#1350]
I was trying to add 2FA on my Laravel Forge account when this occurred. I have 2 identical yubikeys (YubiKey 5 NFC F/W: 5.4.3). When I register a new 2FA, I add it to both keys. I use this strategy in case I loose/break one of the keys to avoid being locked out of my accounts.

Today I tried to add 2FA to my [Laravel Forge](https://forge.laravel.com/) account. When presented the QR code, I scan it with Yubico Authenticator, click add account and then it prompts me to scan my key to confirm. Then I usually do the same thing with the 2nd key (using the same QR code). But when adding the 2nd key, I got an error. At first I thought this site was not allowing adding twice the same secret to two different device. So I tried again, but this time starting with the 2nd key. The same error would happen.

So the problem seems to be specific to one of my YubiKeys. Please let me know if there is something I can do about it.

Thank you!

Here is a log of the error:

```
10:45:51:184 [main] DEBUG c.yubico.authenticator.MainActivity -  Setting FLAG_SECURE (disallow screenshots)
10:45:51:229 [main] DEBUG i3.d -  Current app preferences:
10:45:51:240 [main] TRACE i3.a -  Activity alias 'AliasMainActivity' is enabled: 1
10:45:51:240 [main] DEBUG i3.a -  Enabled USB discovery by setting state of AliasMainActivity to ENABLED
10:45:51:240 [main] DEBUG c.yubico.authenticator.MainActivity -  Starting nfc discovery
10:45:51:247 [main] DEBUG i3.d -  registering change listener
10:45:51:268 [main] INFO  com.yubico.authenticator.Log -  Logging initialized, outputting to Android/logcat [android.logger]
10:45:59:178 [pool-4-thread-1] INFO  g4.h -  Calculating all codes for time=1706283969178
10:46:01:195 [main] ERROR com.yubico.authenticator.Log -  Failed to add account. [android.oath.state] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$d.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$d.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:46:01:196 [main] ERROR com.yubico.authenticator.Log -  Failed to add account [oath.view.add_account_page] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$d.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$d.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:46:07:610 [pool-4-thread-1] INFO  g4.h -  Calculating all codes for time=1706283977609
10:46:09:116 [main] ERROR com.yubico.authenticator.Log -  Failed to add account. [android.oath.state] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:46:09:116 [main] ERROR com.yubico.authenticator.Log -  Failed to add account [oath.view.add_account_page] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:46:28:367 [pool-4-thread-1] INFO  g4.h -  Calculating all codes for time=1706283998367
10:46:29:872 [main] ERROR com.yubico.authenticator.Log -  Failed to add account. [android.oath.state] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:46:29:873 [main] ERROR com.yubico.authenticator.Log -  Failed to add account [oath.view.add_account_page] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:49:44:672 [pool-4-thread-1] INFO  g4.h -  Calculating all codes for time=1706284194672
10:49:46:182 [main] ERROR com.yubico.authenticator.Log -  Failed to add account. [android.oath.state] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:49:46:182 [main] ERROR com.yubico.authenticator.Log -  Failed to add account [oath.view.add_account_page] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:49:56:051 [pool-4-thread-1] INFO  g4.h -  Calculating all codes for time=1706284206051
10:49:57:555 [main] ERROR com.yubico.authenticator.Log -  Failed to add account. [android.oath.state] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:49:57:557 [main] ERROR com.yubico.authenticator.Log -  Failed to add account [oath.view.add_account_page] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:50:26:406 [pool-7-thread-1] INFO  g4.h -  Calculating all codes for time=1706284236406
10:50:26:713 [pool-7-thread-1] ERROR c.y.authenticator.oath.OathManager -  Failed to refresh codesandroid.nfc.TagLostException: Tag was lost.
	at android.nfc.TransceiveResult.getResponseOrThrow(TransceiveResult.java:48)
	at android.nfc.tech.BasicTagTechnology.transceive(BasicTagTechnology.java:154)
	at android.nfc.tech.IsoDep.transceive(IsoDep.java:175)
	at t3.f.A(SourceFile:1)
	at d4.g.l(SourceFile:1)
	at g4.h.n(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager.Q(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager.j(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

10:50:27:915 [main] ERROR com.yubico.authenticator.Log -  Failed to add account. [android.oath.state] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:50:27:916 [main] ERROR com.yubico.authenticator.Log -  Failed to add account [oath.view.add_account_page] (err: PlatformException(b, d4.b: APDU error: 0x6a84, Cause: null, Stacktrace: d4.b: APDU error: 0x6a84
	at d4.g.l(SourceFile:1)
	at g4.h.G(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$c.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$v.b(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.a(SourceFile:1)
	at com.yubico.authenticator.oath.OathManager$j.b(SourceFile:1)
	at t3.i.e(SourceFile:1)
	at t3.i.b(SourceFile:1)
	at t3.g.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, null))
10:51:42:104 [main] INFO  com.yubico.authenticator.Log -  Copying log to clipboard (6.3.1)... [about]
```

**Comment by AdamVe** [comment]
Hi! The response code `0x6a84` is reported by the YubiKey when you add more accounts than the YubiKey can hold, which is, in the case of YubiKey 5 NFC, 32 OATH accounts (see https://support.yubico.com/hc/en-us/articles/360013656980-YubiKey-5-NFC). 

Could you verify how many OATH accounts are stored on your YubiKey?

**Comment by mathieu-pillar** [comment]
I have indeed 32 accounts on the key that is problematic. I must have forgotten to add an account to both keys at some point because the other one is at 31.

The error message is more than cryptic. There is no way I would have figured that out. I was not aware of the limit on the number of account the key can hold.
