### ISSUE TITLE
Bug: icon selection window does not appear

### ISSUE THREAD

**Issue by JaquesBoeno** [Yubico/yubioath-flutter#1399]
when I tried to import icons in the yubico auth app there was absolutely nothing going on, intrigued by this I started the app through the terminal to have access to the logs and realized that when I clicked on the import icons button of the custom icons section he threw me this error:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.
#0      isExecutableOnPath (package:file_picker/src/utils.dart:60)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker/src/linux/file_picker_linux.dart:120)
<asynchronous suspension>
#2      FilePickerLinux.pickFiles (package:file_picker/src/linux/file_picker_linux.dart:23)
<asynchronous suspension>
#3      _ImportActionChip._importAction (package:yubico_authenticator/oath/icon_provider/icon_pack_dialog.dart:177)
<asynchronous suspension>

with a simple analize I realized that I needed to install zenity, because I use kde plasma as my graphical environment in linux, and by default it does not use zenity, but kdialog. Problem solved, zenity installed and now I can import the icons in the app, I opened this Issue so that the bug is fixed and so that others who have the same problem find a paleactive solution by then

**Comment by AdamVe** [comment]
Hi! Thank you for the report, we were not aware of this issue - a library we use uses zenity or similar sw for displaying dialogs. There is already an issue reported in the library’s repository (https://github.com/miguelpruivo/flutter_file_picker/issues/1451).

As a workaround I would recommend one of the following:
- install zenity on your system with (for example with `sudo apt install -y zenity`)
- drag and drop the icon package onto the application when the Custom icons dialog is opened (available since Yubico Authenticator 6.4.0).

https://github.com/Yubico/yubioath-flutter/assets/1954891/b9bd04a3-7cdf-4a18-9770-69c5b9f3f129

You can download an icon pack from https://aegis-icons.github.io/

Let me know if you need any more help.
