### ISSUE TITLE
Scanning QR code stopped working on Mac

### ISSUE THREAD

**Issue by ghost** [Yubico/yubioath-flutter#501]
- Yubico Authenticator version: 5.1.2
- Operating system and version: Mac 10.15.1
- YubiKey model and version: 
- Bug description summary: 

Can't scan QR code like I used to before 10.15 & 5.1.2

Steps to reproduce
---

1. Scan QR code

Expected result
---

QR code scanned

Actual results
---

QR code not scanned

Other info
---

I would like to scan QR codes so I can use my device again.

**Comment by fdennis** [comment]
Thanks for the report.

Can you please double check what version of Yubico Authenticator you are using? The latest should be 5.0.1.

Could you also please check if Yubico Authenticator has access to Input Monitoring? This is new in MacOS Catalina. You can find it in "Security & Privacy" > "Privacy" > "Input Monitoring"

**Comment by AnthonyRonning** [comment]
Oh sorry, that was firmware version. It's 5.0.1. 

And yeah, my Yubico Authenticator requested that permission, I went there to checkbox it, and then restarted the app.

**Comment by fdennis** [comment]
Did it work after restarting or do you still have the same problem?

**Comment by AnthonyRonning** [comment]
Problem still persists.

**Comment by emlun** [comment]
Could you run the application from a terminal with the `--log-level DEBUG` commandline option, try the QR scanner, and post the output here?

**Comment by AdrianMF** [comment]
I'm having the same problem. I'm happy to run from the terminal if you provide the command.

**Comment by AdrianMF** [comment]
It would be nice if there was an image import as a backup

**Comment by braathen** [comment]
Please verify that in Catalina you have the Screen Recording permission set for Yubico Authenticator (System Preferences -> Security & Privacy -> Privacy -> Screen Recording). Additional required settings will also be in Input Monitoring.

I'm running 10.15.2, if I disable the checkbox in Screen Recording it prevents me from scanning QR codes, if I check it - it works. I don't even need to restart the app.

![image](https://user-images.githubusercontent.com/1047597/72434961-395cd600-379d-11ea-9cc6-418b19547e14.png)

Image import is something we have talked about and might look into in the future. Thanks!

**Comment by wade41** [comment]
Scanning doesn't work for me either. I'm on MacOS 10.15.4, is there anything I can do to help get this fixed?

**Comment by dagheyman** [comment]
@wade41 A standard otpauth url should work, following the format [described here](https://github.com/google/google-authenticator/wiki/Key-Uri-Format). The issue you linked is about handling those links directly, not when parsed from QR code.

Could you give us any more info about the QR code so we can look into it? Maybe name the service, or post the string in the QR code with the secret removed.

**Comment by wade41** [comment]
It's from a project I'm working on. Utilizing ttps://github.com/endroid/qr-code to generate the QR code and https://github.com/Spomky-Labs/otphp to generate the provisioning uri.

Here's the otpauth url:

otpauth://totp/admin.Application%3Asam%40u-lab.nl?issuer=admin.Application&secret=

**Comment by dagheyman** [comment]
uri looks fine, I'm able to add it with ykman:

```
$ ykman oath uri "otpauth://totp/admin.Application%3Asam%40u-lab.nl?issuer=admin.Application&secret=abba"
$ ykman oath code
admin.Application:sam@u-lab.nl  742944
```
Do you have an example QR code picture as well?

**Comment by wade41** [comment]
Sure thing, here you go. I shortened the secret bit in this to abba like your comment.

![qrcode](https://user-images.githubusercontent.com/45849554/80574560-5c389080-8a02-11ea-99b0-2c7362c98775.png)

**Comment by apastuszak** [comment]
I am on MacOS Big Sur, and this still doesn't work. I have all permissions set properly. Please let me know anything I can do to help troubleshoot the issue.

**Comment by abendt** [comment]
just bought a new Yubikey, just ran into this issue when trying to setup with https://www.docusign.com/. here is the output from `/Applications/Yubico\ Authenticator.app/Contents/MacOS/yubioath-desktop --log-level DEBUG`

```
2021-03-03T21:11:36+0100 ERROR [yubikey.parse_qr:558] Failed to parse uri
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 556, in parse_qr
    CredentialData.from_uri(qrdecode.decode_qr_data(qr))))
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ykman/oath.py", line 124, in from_uri
    raise ValueError('Invalid URI scheme')
ValueError: Invalid URI scheme
2021-03-03T21:11:40+0100 ERROR [yubikey.parse_qr:558] Failed to parse uri
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 556, in parse_qr
    CredentialData.from_uri(qrdecode.decode_qr_data(qr))))
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ykman/oath.py", line 124, in from_uri
    raise ValueError('Invalid URI scheme')
ValueError: Invalid URI scheme
```

**Comment by vosscodes** [comment]
Same issue, MacOS 12.2.1 and authenticator 5.1.0

```
2022-03-31T09:11:51-0400 ERROR [yubikey.parse_qr:925] Failed to parse uri
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 923, in parse_qr
    CredentialData.parse_uri(data)))
  File "/Applications/Yubico Authenticator.app/Contents/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yubikit/oath.py", line 110, in parse_uri
    raise ValueError("Invalid URI scheme")
ValueError: Invalid URI scheme
```

The app only requested screen recording, but I granted it input monitoring as well. No change with both.

**Comment by bergerj** [comment]
Had an issue but once I added:

Screen Recording permission set for Yubico Authenticator (System Preferences -> Security & Privacy -> Privacy -> Screen Recording). Additional required settings will also be in Input Monitoring.

Running Monterey 12.3.1
Yubico Authenticator v5.1.0

**Comment by vosscodes** [comment]
> @vosscodes Can it scan some qr codes or do you run into the same issue with every single qr code?

sorry for the delay - not sure how I missed this. I only attempted two sources (several times with regenerated codes), but no luck with either. Unfortunately this was a corporate device that I no longer have, so I can't attempt again or get any more details.

**Comment by ruario** [comment]
I also have this issue. Both Screen Recording and Input Monitoring permissions have been gived to Yubico Authenticator v5.1.0. I am running macOS 12.5.1

**Comment by ruario** [comment]
FWIW I have a QR code scanning app "QR Capture v2.5.6 (43) by Marek Hrušovský" (from the App Store), which also uses Screen Recording permissions read QR codes on screen. It can scan these no problem. Indeed this is how I am now getting the details across and into Yubico Authenticator on sites that do not give me a way to copy thr raw secret.

I mention this to point out it is not some new limitation in recent macOS. This is possible, it is just that Yubico Authenticator v5.1.0 fails due to some bug.

**Comment by fdennis** [comment]
@ruario We are working on a newer version of the app. If you have the time you can try out the beta here https://www.yubico.com/products/yubico-authenticator/yubico-authenticator-desktop-beta/ . It would be interesting for us to know if this works better or not. Please keep in mind that this is a beta version. Thanks!

**Comment by dainnilsson** [comment]
Yubico Authenticator 6.0 has now been released and uses a new codebase. As such, this issue has been marked with the `legacy` label, and will be automatically closed in 7 days. If this issue is still relevant to Yubico Authenticator 6, please comment on the issue saying so, and it will be kept open (or be re-opened). Sorry for the inconvenience!
