### ISSUE TITLE
Yubico authenticator doesn't detect yubikeys after sleep mode

### ISSUE THREAD

**Issue by Aaron-P** [Yubico/yubioath-flutter#554]
- Yubico Authenticator version: 5.0.2
- Operating system and version: Windows 10 1903
- YubiKey model and version: YubiKey 5 Nano firmware 5.2.4 and YubiKey 5 NFC
- Bug description summary: If the computer is put to sleep and woken up multiple times with a yubikey inserted and the application running, the application cannot detect any yubikeys anymore until either the system is restarted, or all yubikeys removed and the application restarted.

Steps to reproduce
---

With the application running and yubikey inserted put the computer to sleep and then wake it up.  The application will no longer recognized yubikeys, even if the application is restarted or the key is removed and reinserted (while running) or new keys are inserted, until either the system is restarted or all yubikeys removed and the application is restarted.  Sometimes takes several iterations of sleep/wake before it triggers the bug.

Expected result
---

The application should be able to read the yubikeys and generate one time passwords from it.

Actual results
---

The application either doesn't detect the yubikey at all and gives a message saying to insert a yubikey, or the yubikey is recognized but attempting to generate a one time password fails with a generic error.

Other info
---

**Trace log when attempting to use the application with the already-inserted YubiKey 5 Nano:**

2020-03-08T16:05:07-0500 INFO [ykman.logging_setup.setup:58] Initialized logging for ykman version: 3.1.1
2020-03-08T16:05:07-0500 ERROR [yubikey.wrapped:123] Uncaught exception
Traceback (most recent call last):
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\driver_ccid.py", line 288, in kill_scdaemon
    from win32com.client import GetObject
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ModuleNotFoundError: No module named 'win32api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 103, in wrapped
    return f(*args, **kwargs)
  File "qrc:///py/yubikey.py", line 318, in refresh_devices
    self._devices = self._get_devices(otp_mode)
  File "qrc:///py/yubikey.py", line 243, in _get_devices
    for dev in list_devices(transport):
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\descriptor.py", line 170, in list_devices
    for d in _list_drivers(transports):
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\descriptor.py", line 156, in _list_drivers
    for dev in open_ccid():
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\driver_ccid.py", line 341, in open_devices
    if try_again and kill_scdaemon():
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\driver_ccid.py", line 301, in kill_scdaemon
    pids = subprocess.check_output(
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command 'ps ax | grep scdaemon | grep -v grep | awk '{ print $1 }'' returned non-zero exit status 1.

**Trace log when attempting to use the application with a newly inserted YubiKey 5 NFC.**

2020-03-08T16:10:54-0500 DEBUG [ykman.device.__init__:198] Read config from device...
2020-03-08T16:10:54-0500 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040008a000000527471117'
2020-03-08T16:10:54-0500 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'5669727475616c206d6772202d2046572076657273696f6e20352e322e349000'
2020-03-08T16:10:54-0500 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'001d000000'
2020-03-08T16:10:54-0500 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'2e0102023f0302023f020400acd90104010105030502040602000007010f0801000d02023f0e02023f0a01000f01009000'
2020-03-08T16:10:54-0500 DEBUG [ykman.device.__init__:200] Success!
2020-03-08T16:10:54-0500 DEBUG [ykman.device.__init__:289] Identified YubiKey 5
2020-03-08T16:10:54-0500 DEBUG [ykman.driver_ccid.send_apdu:228] SEND: b'00a4040007a0000005272101'
2020-03-08T16:10:54-0500 DEBUG [ykman.driver_ccid.send_apdu:230] RECV: b'790305020471081ef20c67b0df60e27408ff2543c4b9408aa37b01019000'
2020-03-08T16:10:54-0500 ERROR [yubikey.wrapped:123] Uncaught exception
Traceback (most recent call last):
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\driver_ccid.py", line 288, in kill_scdaemon
    from win32com.client import GetObject
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ModuleNotFoundError: No module named 'win32api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 103, in wrapped
    return f(*args, **kwargs)
  File "qrc:///py/yubikey.py", line 318, in refresh_devices
    self._devices = self._get_devices(otp_mode)
  File "qrc:///py/yubikey.py", line 243, in _get_devices
    for dev in list_devices(transport):
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\descriptor.py", line 170, in list_devices
    for d in _list_drivers(transports):
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\descriptor.py", line 156, in _list_drivers
    for dev in open_ccid():
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\driver_ccid.py", line 341, in open_devices
    if try_again and kill_scdaemon():
  File "C:\Program Files\Yubico\Yubico Authenticator\pymodules\ykman\driver_ccid.py", line 301, in kill_scdaemon
    pids = subprocess.check_output(
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command 'ps ax | grep scdaemon | grep -v grep | awk '{ print $1 }'' returned non-zero exit status 1.
2020-03-08T16:10:54-0500 DEBUG [ykman.driver_ccid.__del__:273] Destroy <ykman.driver_ccid.CCIDDriver object at 0x00000210EC7AEC70>
2020-03-08T16:10:54-0500 DEBUG [ykman.driver_ccid.close:269] Close <ykman.driver_ccid.CCIDDriver object at 0x00000210EC7AEC70>

**Comment by gbcox** [comment]
Noticed the same issue with Fedora 31.

**Comment by dagheyman** [comment]
Thanks for the detailed report, we'll look into it.

**Comment by dainnilsson** [comment]
Yubico Authenticator 6.0 has now been released and uses a new codebase. As such, this issue has been marked with the `legacy` label, and will be automatically closed in 7 days. If this issue is still relevant to Yubico Authenticator 6, please comment on the issue saying so, and it will be kept open (or be re-opened). Sorry for the inconvenience!
