### ISSUE TITLE
ScanQR code doesnt work when using Manjaro and i3 window manager

### ISSUE THREAD

**Issue by unchainedio** [Yubico/yubioath-flutter#655]
Yubico Authenticator version: 5.04
Operating system and version: Manjaro rolling release
YubiKey model and version: Yubikey 5NFC
Bug description summary: QR code scan does not work
Steps to reproduce
Install Manjaro. Or on Arch Linux. Install the authenticator App

Using i3 with yubico window tiled next to QR code, i am unable to scan QR 

Expected result
I should be able to scan QR codes from the screen when using i3 window manager.

Actual results
QR Code was not found

![image](https://user-images.githubusercontent.com/22932825/89148668-ccebcd80-d55a-11ea-8206-03fe1b2ac84a.png)

**Comment by fdennis** [comment]
Thanks for lettings us know.
We will take a look at this.

**Comment by unchainedio** [comment]
any news on this?  seems like it happens on diff distros

**Comment by JonasVerhofste** [comment]
When running with `--log-level DEBUG` I get the following error:
```
2020-08-30T13:56:04+0200 ERROR [yubikey.parse_qr:558] Failed to parse uri
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 556, in parse_qr
    CredentialData.from_uri(qrdecode.decode_qr_data(qr))))
  File "/usr/lib/python3.8/site-packages/ykman/oath.py", line 124, in from_uri
    raise ValueError('Invalid URI scheme')
ValueError: Invalid URI scheme
```

So not sure if it's reading the QR wrong and passing garbage to ykman, or if it's a bug in ykman.

**Comment by dainnilsson** [comment]
Yubico Authenticator 6.0 has now been released and uses a new codebase. As such, this issue has been marked with the `legacy` label, and will be automatically closed in 7 days. If this issue is still relevant to Yubico Authenticator 6, please comment on the issue saying so, and it will be kept open (or be re-opened). Sorry for the inconvenience!
