### ISSUE TITLE
Not working on Raspberry Pi 3b

### ISSUE THREAD

**Issue by vanderblugen** [Yubico/yubioath-flutter#668]
- Yubico Authenticator version:   3.0.1-2
- Operating system and version:   Raspberry Pi OS (Raspbian GNU/Linux 10 (buster))
- YubiKey model and version:  5 NFC
- Bug description summary: 

Steps to reproduce
---

Installed yubico authenticator
`sudo apt-get install yubioath-desktop -y`

Attempted to run the application by opening it and it just displays 'Insert a YubiKey'
even when the YubiKey is inserted and will not show the timed tokens.

Expected result
---

Display the timed tokens and ask for password if a password is specified

Actual results
---

Just displays the 'Insert a Yubikey'

Other info
---

It installs just fine but doesn't pull the time based tokens.  Just shows the insert key message.
It is reading the key, if click on settings and enable the 'Read from slot 1' and or Read from slot 2' it'll show a single token titled 'YubiKey slot 1' (or 2).

**Comment by fdennis** [comment]
Hi,
Thanks for the report.
Is pcscd running?

**Comment by vanderblugen** [comment]
pcscd is running

**Comment by fdennis** [comment]
We do not officially support raspberry pi, but I do not see any reason why it should not work. It should be available on Debian https://packages.debian.org/sid/yubioath-desktop

What version of Yubico Authenticator are you using? Could you try running with `--log-level DEBUG` and post the result here?

**Comment by vanderblugen** [comment]
Oh hmm, that's interesting.

If I run `yubioath` it seems to work, granted in the commandline, but if I run the gui `yubioath-gui` the codes don't populate like they do in windows.

I cannot run `yubioath-gui --log-level DEBUG` nor `yubioath --log-level DEBUG`.  Get an error for each of them.

Version is 3.0.1 for yubioath

Maybe it has to do with the password cause it never populates in the gui

**Comment by fdennis** [comment]
@vanderblugen Latest version of Yubico Authenticator is 5.0.4. [This](https://packages.debian.org/sid/yubioath-desktop) is what you need, if you are on Debian.

**Comment by vanderblugen** [comment]
Why didn't that version install when I ran `sudo apt install yubioath-desktop`?

**Comment by fdennis** [comment]
@vanderblugen Have you made any progress on this? You can find instructions [here](https://github.com/Yubico/yubioath-desktop/blob/master/doc/development.adoc) on how we are compiling. Not sure whether that will solve your issue.

**Comment by vanderblugen** [comment]
The code will not compile on a raspberry pi.  

In order to add the repository with `sudo add-apt-repository -y ppa:yubico/stable` you have to be able to add that in with `sudo apt-get install software-properties-common` but immediately get an error of 

```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster
```

I was able to get qmake installed thru some of the instructions found [here ](https://www.raspberrypi.org/forums/viewtopic.php?t=69163) but was unable to get it to compile.

I did double check and make sure that I had everything installed by running `sudo apt-get install yubikey-manager yubioath-desktop yubikey-personalization-gui -y`.  I know that's overkill, but just trying to get it working.


No luck on it.

**Comment by dainnilsson** [comment]
Yubico Authenticator 6.0 has now been released and uses a new codebase. As such, this issue has been marked with the `legacy` label, and will be automatically closed in 7 days. If this issue is still relevant to Yubico Authenticator 6, please comment on the issue saying so, and it will be kept open (or be re-opened). Sorry for the inconvenience!
