### ISSUE TITLE
Yubico Authenticator does not recognize touch on Manjaro Linux

### ISSUE THREAD

**Issue by harmtemolder** [Yubico/yubioath-flutter#771]
- Yubico Authenticator version: `5.1.0`
- Operating system and version: `Manjaro Linux 21.2.1`
- YubiKey model and version: `YubiKey 5C 5.4.3`
- Bug description summary: Yubico Authenticator does not recognize touch

Steps to reproduce
---

1. Connect the YubiKey
2. Start Yubico Authenticator
3. Double-click one of the entries so that "Touch your YubiKey" appears
4. Touch the YubiKey

Expected result
---

A one-time password should be revealed. And I believe LEDs should flash on the YubiKey, right?

Actual results
---

Nothing happened: the entry remained `*** ***`. And no lights.

Other info
---

I might have updated some software, but haven't changed the setup of my YubiKey between when it was working and now

When I run `yubioath-desktop --log-level DEBUG` a couple of things catch my eye:

```
2022-01-15T06:59:59+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw7'
2022-01-15T06:59:59+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw6'
2022-01-15T06:59:59+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw5'
2022-01-15T06:59:59+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw4'
2022-01-15T06:59:59+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw3'
2022-01-15T06:59:59+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw2'
2022-01-15T06:59:59+0100 DEBUG [ykman.hid.linux.list_devices:108] Failed opening HID device
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ykman/hid/linux.py", line 103, in list_devices
    with open(hidraw, "rb") as f:
PermissionError: [Errno 13] Permission denied: '/dev/hidraw8'
2022-01-15T06:59:59+0100 DEBUG [fido2.hid.linux.list_descriptors:89] Found CTAP device: /dev/hidraw1
2022-01-15T06:59:59+0100 DEBUG [fido2.hid.linux.list_descriptors:93] Skip device: [Errno 13] Permission denied: '/dev/hidraw7'
2022-01-15T06:59:59+0100 DEBUG [fido2.hid.linux.list_descriptors:93] Skip device: [Errno 13] Permission denied: '/dev/hidraw6'
2022-01-15T06:59:59+0100 DEBUG [fido2.hid.linux.list_descriptors:93] Skip device: [Errno 13] Permission denied: '/dev/hidraw5'
2022-01-15T06:59:59+0100 DEBUG [fido2.hid.linux.list_descriptors:93] Skip device: [Errno 13] Permission denied: '/dev/hidraw4'
2022-01-15T06:59:59+0100 DEBUG [fido2.hid.linux.list_descriptors:93] Skip device: [Errno 13] Permission denied: '/dev/hidraw3'
2022-01-15T06:59:59+0100 DEBUG [fido2.hid.linux.list_descriptors:93] Skip device: [Errno 13] Permission denied: '/dev/hidraw2'
2022-01-15T06:59:59+0100 DEBUG [fido2.hid.linux.list_descriptors:93] Skip device: [Errno 13] Permission denied: '/dev/hidraw8'
```

Then a couple of `SEND` and `RECV` back and forth, then this:

```
2022-01-15T06:59:59+0100 DEBUG [yubikey._get_fido_status:268] Failed to read CTAP info
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 254, in _get_fido_status
    ctap2 = Ctap2(conn)
  File "/usr/lib/python3.10/site-packages/fido2/ctap2/base.py", line 643, in __init__
    self._info = self.get_info()
  File "/usr/lib/python3.10/site-packages/fido2/ctap2/base.py", line 695, in get_info
    return self.send_cbor(Ctap2.CMD.GET_INFO, parse=Info)
  File "/usr/lib/python3.10/site-packages/fido2/ctap2/base.py", line 672, in send_cbor
    response = self.device.call(CTAPHID.CBOR, request, event, on_keepalive)
  File "/usr/lib/python3.10/site-packages/fido2/hid/__init__.py", line 191, in call
    raise Exception("Wrong channel")
Exception: Wrong channel
```

Then the `hidraw` bit keeps repeating.

When I double-click an entry I see a `SEND`, `RECV`, `SEND`, but then the last `RECV` is missing. Like the YubiKey is not responding

I'm happy to share the entire log, if that helps. Just to be safe: should I redact any of the IDs or fingerprints in there?

**Comment by harmtemolder** [comment]
Because of the `permission` error I  thought to run `sudo yubioath-desktop --log-level DEBUG`. The result is the same, but no `permission` error anymore. I do get this:

```
2022-01-15T07:15:00+0100 DEBUG [yubikey._get_fido_status:268] Failed to read CTAP info
Traceback (most recent call last):
  File "qrc:///py/yubikey.py", line 254, in _get_fido_status
    ctap2 = Ctap2(conn)
  File "/usr/lib/python3.10/site-packages/fido2/ctap2/base.py", line 643, in __init__
    self._info = self.get_info()
  File "/usr/lib/python3.10/site-packages/fido2/ctap2/base.py", line 695, in get_info
    return self.send_cbor(Ctap2.CMD.GET_INFO, parse=Info)
  File "/usr/lib/python3.10/site-packages/fido2/ctap2/base.py", line 672, in send_cbor
    response = self.device.call(CTAPHID.CBOR, request, event, on_keepalive)
  File "/usr/lib/python3.10/site-packages/fido2/hid/__init__.py", line 210, in call
    raise CtapError(struct.unpack_from(">B", recv)[0])
fido2.ctap.CtapError: CTAP error: 0x06 - CHANNEL_BUSY
```

And the following line keeps repeating:

```
2022-01-15T07:15:00+0100 DEBUG [fido2.hid.linux.list_descriptors:89] Found CTAP device: /dev/hidraw1
```

**Comment by harmtemolder** [comment]
One more thing: the Yubico Authenticator app on Android works just fine with the same YubiKey

**Comment by compieter-gh** [comment]
For me it reconizes the touch but the key i get is invalid. Which on android it works fine.

**Comment by dainnilsson** [comment]
Yubico Authenticator 6.0 has now been released and uses a new codebase. As such, this issue has been marked with the `legacy` label, and will be automatically closed in 7 days. If this issue is still relevant to Yubico Authenticator 6, please comment on the issue saying so, and it will be kept open (or be re-opened). Sorry for the inconvenience!
