### ISSUE TITLE
Unhandled Error prevents yubikey recognition

### ISSUE THREAD

**Issue by jlopp** [Yubico/yubioath-flutter#804]
- Yubico Authenticator version: 5.1.0
- Operating system and version: Ubuntu 22.04
- YubiKey model and version: Yubikey 5 NFC (5.1.1) [OTP+FIDO+CCID]
- Bug description summary: 

I have been using Yubioath-desktop up to version 5.0.4 without any issues on my machine, but updating to 5.1.0 makes it impossible to retrieve OTP codes from the yubikey.

Steps to reproduce
---

I ran yubioath-desktop-5.1.0-linux.AppImage on my machine with my yubikey 5 plugged in.

Expected result
---

I expected to see a list of services for which I've created OTP entries.

Actual results
---

Yubico Authenticator launches but just says "Insert your YubiKey" while the binary logs the following errors:

```
~/Downloads/yubioath-desktop-5.1.0-linux.AppImage 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Unhandled PyOtherSide error: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 22, in <module>
    from fido2.ctap2 import Ctap2, ClientPin, FPBioEnrollment, CredentialManagement, CaptureError

ImportError: cannot import name 'Ctap2' from 'fido2.ctap2' (/home/jameson/.local/lib/python3.8/site-packages/fido2/ctap2.py)
)
Unhandled PyOtherSide error: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.check_descriptors' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'success' of undefined undefined
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.is_win_non_admin' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'winNonAdmin' of undefined undefined
```

**Comment by dainnilsson** [comment]
Yubico Authenticator 6.0 has now been released and uses a new codebase. As such, this issue has been marked with the `legacy` label, and will be automatically closed in 7 days. If this issue is still relevant to Yubico Authenticator 6, please comment on the issue saying so, and it will be kept open (or be re-opened). Sorry for the inconvenience!
