### ISSUE TITLE
ValueError: Unsupported Connection type

### ISSUE THREAD

**Issue by LethalNL1** [Yubico/yubioath-flutter#876]
**System information:**
OS: OpenSUSE MicroOS
Authenticator Version: 6.0.2b-linux

**Description:**
Error "The name org.a11y.Bus was not provided by any .service files" occured, fixed it by installing at-spi2-core.

Running the bin with above configuration fails, shows "Failed to open smart card connection. Make sure pcscd is intalled and running." in app. Installed, started and enabled pcscd, it is running. 

sudo systemctl status pcscd:

```
● pcscd.service - PC/SC Smart Card Daemon
     Loaded: loaded (/usr/lib/systemd/system/pcscd.service; indirect; preset: disabled)
     Active: active (running) since Wed 2022-12-14 21:38:13 CET; 16min ago
TriggeredBy: ● pcscd.socket
```

./authenticator shows:
```
22:01:54.921 [desktop.init] INFO: Logging initialized, outputting to stderr
22:01:54.923 [desktop.init] INFO: Starting Helper subprocess: /home/janjacob/Applications/yubioath-desktop-release-linux/helper/authenticator-helper
22:01:54.925 [desktop.init] INFO: Helper process started
/home/janjacob/Applications/yubioath-desktop-release-linux/helper/authenticator-helper
22:01:55.271 [helper.ykman.logging] INFO: Logging at level: INFO
22:01:55.271 [helper.helper.device] INFO: Log level set to: INFO
22:01:55.702 [desktop.devices] INFO: USB state change
{"data":{"state":-5582327410880417976,"pids":{"1031":1}},"actions":["get","scan"],"children":{"16538842":{"pid":1031,"name":"YubiKey 5C","serial":16538842}}}
22:01:55.704 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.smartcard.SmartCardConnection'>
Traceback (most recent call last):
  File "helper/device.py", line 279, in get_data
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
22:01:55.704 [helper.helper.device] WARNING: Unable to connect via <class 'yubikit.core.otp.OtpConnection'>
Traceback (most recent call last):
  File "helper/device.py", line 279, in get_data
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
22:01:55.770 [desktop.devices] INFO: USB state updated, unaccounted for: {}
22:01:55.793 [helper.helper.device] WARNING: Error opening connection
Traceback (most recent call last):
  File "helper/device.py", line 288, in ccid
  File "helper/device.py", line 272, in _create_connection
  File "ykman/device.py", line 254, in open_connection
ValueError: Unsupported Connection type
```

Other applications using my Yubikey 5C work fine (eg. keepassxc flatpak, firefox flatpak). The Yubico Authenticator flatpak gives the same error upon launch, not sure if it has the same cause or related.

**Comment by LethalNL1** [comment]
Solution found in #754 .

        > make sure you have `libccid` installed. Then restart pcscd and should be good.
> 
> On the other hand i recommend using the packaged tools as those appimages.

For those that use openSUSE the package is `pcsc-ccid` (maybe its for every RPM based Distro)

_Originally posted by @hoferbeck in https://github.com/Yubico/yubioath-flutter/issues/754#issuecomment-1030866803_
