### ISSUE TITLE
Codes not computed directly after NFC tap which unlocks OATH session

### ISSUE THREAD

**Issue by AdamVe** [Yubico/yubioath-flutter#967]
Recreated from https://github.com/Yubico/yubioath-flutter/issues/899#issuecomment-1437240849 

Something seems to happen when the oath device is tapped for the second time after (the after the password is typed) that the codes are not computed straight away, but simply tapping the device a third time works and all subsequent taps work fine.

<details>
  <summary>Second tap (after typing the password)</summary>

```
[android.logger] INFO: Logging initialized, outputting to Android/logcat
[about] DEBUG: Log level set to TRAFFIC
[AppPreferences] DEBUG: unregistered change listener
[MainActivity] DEBUG: Stopped usb discovery
[MainActivity] DEBUG: Stopped nfc discovery
[android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: inactive
[android.window_state_provider] DEBUG: Updated windowState to WindowState(focused: false, visible: false, active: false)
[android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: paused
[android.window_state_provider] DEBUG: Ignoring appLifecycleStateChange
[MainActivity] DEBUG: Starting nfc discovery
[AppPreferences] DEBUG: registering change listener
[android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: resumed
[android.window_state_provider] DEBUG: Updated windowState to WindowState(focused: true, visible: true, active: true)
[yubikit] TRAFFIC: nfc connection opened
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01
[yubikit] TRAFFIC: received: 79 03 ...data blob... 90 00
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 20 01 01
[yubikit] TRAFFIC: received: 69 82
[OathManager] ERROR: Failed to recognize this OATH device.
[OathManager] DEBUG: Successfully read Oath session info (and credentials if unlocked) from connected key
[yubikit] TRAFFIC: nfc connection closed
[yubikit] TRAFFIC: nfc connection opened
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01
[yubikit] TRAFFIC: received: 79 03 ...data blob... 90 00
[OathManager] DEBUG: Cancelled Dialog Unlocking
[android.oath.state] DEBUG: Calling unlock failed with exception: PlatformException(CancellationException, java.util.concurrent.CancellationException, Cause: null, Stacktrace: java.util.concurrent.CancellationException
at com.yubico.authenticator.oath.OathManager$u.q(Unknown Source:49)
at com.yubico.authenticator.oath.OathManager$u.u(Unknown Source:8)
at com.yubico.authenticator.oath.OathManager$u.b(Unknown Source:2)
at g3.j$d.q(Unknown Source:30)
at g3.j$d.t(Unknown Source:8)
at g3.j$d.j(Unknown Source:4)
at w5.b.b(Unknown Source:7)
at r5.h.c(Unknown Source:49)
at r5.g.c(Unknown Source:0)
at g3.j.d(Unknown Source:70)
at g3.j.a(Unknown Source:0)
at g3.j$a.q(Unknown Source:42)
at g3.j$a.t(Unknown Source:11)
at g3.j$a.i(Unknown Source:6)
at g3.e$b.q(Unknown Source:43)
at c5.a.h(Unknown Source:11)
at kotlinx.coroutines.internal.g.b(Unknown Source:132)
at w5.a.c(Unknown Source:16)
at w5.a.d(Unknown Source:5)
at r5.j0.b(Unknown Source:41)
at r5.a.B0(Unknown Source:0)
at r5.h.a(Unknown Source:22)
at r5.g.a(Unknown Source:0)
at r5.h.b(Unknown Source:12)
at r5.g.b(Unknown Source:0)
at g3.e.d(Unknown Source:49)
at g3.e.a(Unknown Source:0)
at g3.d.f(Unknown Source:4)
at r4.j$a.a(Unknown Source:17)
at f4.c.j(Unknown Source:18)
at f4.c.k(Unknown Source:20)
at f4.c.g(Unknown Source:0)
at f4.b.run(Unknown Source:12)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7870)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
, null)
[yubikit] TRAFFIC: sent: 00 a3 ...data blob... 9b af
[yubikit] TRAFFIC: received: 75 14 ...data blob... 90 00
[OathManager] ERROR: Failed to connect to CCID
[OathManager] ERROR(details): java.lang.IllegalStateException: Already resumed
[yubikit] TRAFFIC: nfc connection closed
[about] INFO: Copying log to clipboard (6.1.1)...
[android.logger] DEBUG: Getting logs...
```
</details>

<details>
  <summary>Third and subsequent taps</summary>

```
[AppPreferences] DEBUG: unregistered change listener
[MainActivity] DEBUG: Stopped usb discovery
[MainActivity] DEBUG: Stopped nfc discovery
[android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: inactive
[android.window_state_provider] DEBUG: Updated windowState to WindowState(focused: false, visible: false, active: false)
[android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: paused
[android.window_state_provider] DEBUG: Ignoring appLifecycleStateChange
[MainActivity] DEBUG: Starting nfc discovery
[AppPreferences] DEBUG: registering change listener
[OathManager] DEBUG: Removing NFC data after resume.
[android.window_state_provider] DEBUG: appLifecycleStateChange triggered with: resumed
[android.window_state_provider] DEBUG: Updated windowState to WindowState(focused: true, visible: true, active: true)
[android.devices] DEBUG: Yubikey was detached.
[yubikit] TRAFFIC: nfc connection opened
[yubikit] TRAFFIC: sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01
[yubikit] TRAFFIC: received: 79 03 ...data blob... 90 00
[yubikit] TRAFFIC: sent: 00 a3 ...data blob... c1 51
[yubikit] TRAFFIC: received: 75 14 ...data blob... 90 00
[yubikit] TRAFFIC: sent: 00 a4 ...data blob... b4 b7
[yubikit] TRAFFIC: received: 71 17 ...data blob... 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 31 33 ...data blob... 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 19 47 ...data blob... 61 fc
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: a4 0c ...data blob... 61 8e
[yubikit] TRAFFIC: sent: 00 a5 00 00 00
[yubikit] TRAFFIC: received: 3a 63 ...data blob...90 00
[yubikit] TRAFFIC: sent: 00 a4 ...data blob... 01 01
[yubikit] TRAFFIC: received: 6b 00
[OathManager] ERROR: Failed to recognize this OATH device.
[OathManager] DEBUG: Successfully read Oath session info (and credentials if unlocked) from connected key
[yubikit] TRAFFIC: nfc connection closed
[about] INFO: Copying log to clipboard (6.1.1)...
[android.logger] DEBUG: Getting logs...
```

</details>

**Comment by AdamVe** [comment]
When reproducing with 6.3.0, the flow looks as follows

<details>
 <summary>Traffic logs (test data)</summary> 
 <summary>First tap</summary>

```
12:40:49.248 26863-26940 v3.f        D  nfc connection opened
12:40:49.249 26863-26940             V  sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01 
12:40:49.263 26863-26940             V  received: 79 03 05 04 03 71 08 fd d8 b5 c4 0a 8a 79 8b 74 08 9c 0c 07 a7 ff 35 36 af 7b 01 01 90 00 
12:40:49.264 26863-26940 h4.h        D  OATH session initialized (version=5.4.3, isAccessKeySet=true)
12:40:49.268 26863-26940 v3.f        V  sent: 00 a4 04 00 08 a0 00 00 05 27 47 11 17 
12:40:49.276 26863-26940             V  received: 56 69 72 74 75 61 6c 20 6d 67 72 20 2d 20 46 57 20 76 65 72 73 69 6f 6e 20 35 2e 34 2e 33 90 00 
12:40:49.277 26863-26940 g4.e        D  Management session initialized for connection=f, version=5.4.3
12:40:49.277 26863-26940 v3.f        V  sent: 00 1d 00 00 00 
12:40:49.287 26863-26940             V  received: 2e 01 02 03 3f 03 02 02 3b 02 04 01 25 a7 ab 04 01 81 05 03 05 04 03 06 02 00 00 07 01 0f 08 01 00 0d 02 03 3f 0e 02 02 3b 0a 01 00 0f 01 00 90 00 
12:40:49.287 26863-26940 i4.a        D  Read info DeviceInfo{config=DeviceConfig{enabledCapabilities={NFC=571, USB=571}, autoEjectTimeout=0, challengeResponseTimeout=15, deviceFlags=0}, serialNumber=19244971, version=5.4.3, formFactor=USB_A_KEYCHAIN, supportedCapabilities={NFC=831, USB=831}, isLocked=false, isFips=true, isSky=false}
12:40:49.299 26863-26863 com....ger  D  Successfully read Oath session info (and credentials if unlocked) from connected key
12:40:49.301 26863-26940 v3.f        D  nfc connection closed
```

<summary>Here we enter the password (IME keyboard show and hidden on submit)</summary>

```
12:40:49.697 26863-26863 ImeTracker  I  com.yubico.yubioath:55cdd574: onShown
12:41:00.503 26863-26863             I  com.yubico.yubioath:d1831009: onRequestShow at ORIGIN_CLIENT_SHOW_SOFT_INPUT reason SHOW_SOFT_INPUT
12:41:00.504 26863-26863 Inpu...ger  D  showSoftInput() view=io.flutter.embedding.android.z{617d919 VFE...... .F...... 0,0-1080,2400 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
12:41:00.512 26863-26863 Inse...ler  D  show(ime(), fromIme=true)
12:41:00.512 26863-26863 ImeTracker  I  com.yubico.yubioath:d1831009: onCancelled at PHASE_CLIENT_APPLY_ANIMATION
12:41:01.427 26863-26863             I  com.yubico.yubioath:b9c21817: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT
12:41:01.439 26863-26863 Wind...her  W  sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@65529423 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@d361724
12:41:01.743 26863-26863 ImeTracker  I  com.yubico.yubioath:57feb8cc: onRequestHide at ORIGIN_CLIENT_HIDE_SOFT_INPUT reason HIDE_SOFT_INPUT_BY_INSETS_API
12:41:01.744 26863-26863             I  com.yubico.yubioath:b9c21817: onHidden
```

<summary>Here we tap the nfc key again</summary>

```
12:41:03.955 26863-26940 v3.f        D  nfc connection opened
12:41:03.956 26863-26940             V  sent: 00 a4 04 00 08 a0 00 00 05 27 21 01 01 
12:41:03.966 26863-26940             V  received: 79 03 05 04 03 71 08 fd d8 b5 c4 0a 8a 79 8b 74 08 06 d6 0e d6 07 9d c9 57 7b 01 01 90 00 
12:41:03.967 26863-26940 h4.h        D  OATH session initialized (version=5.4.3, isAccessKeySet=true)
12:41:03.976 26863-26940             D  Unlocking session
12:41:03.978 26863-26940 v3.f        V  sent: 00 a3 00 00 20 75 14 f6 e2 a1 09 48 62 74 2d d3 56 26 68 db 46 25 60 7b 95 ab f2 74 08 44 5c 5d 31 f3 5d c9 44 
12:41:03.989 26863-26940             V  received: 75 14 29 1e fe 13 7b e4 f6 77 03 07 9e 22 9b 23 8d 4c 19 65 36 2f 90 00 
12:41:03.991 26863-26940 h4.h        I  Calculating all codes for time=1695811273991
12:41:03.992 26863-26940 v3.f        V  sent: 00 a4 00 01 0a 74 08 00 00 00 00 03 5e 88 c2 
12:41:04.003 26863-26940             V  received: 71 07 61 64 61 3a 61 64 61 76 05 06 00 0e 4f f2 90 00 
12:41:04.011 26863-26863 com....ger  D  Successfully read Oath session info (and credentials if unlocked) from connected key
12:41:04.021 26863-26940 v3.f        D  nfc connection closed
```
</details>

This behaves as expected, the codes are computed exactly one time after unlocking. If there are any codes which need extra calculation, that would happen as well.
